const fs = require('fs');
const p = require('path');

const out = p.resolve(__dirname, 'apps/web/src/app/chat/page.tsx');

const code = [
  "'use client';",
  "",
  "import { useEffect, useRef, useState } from 'react';",
  "import type { RefObject } from 'react';",
  "import { useRouter } from 'next/navigation';",
  "import { useAuthStore } from '@/store/auth';",
  "import { useChatStore } from '@/store/chat';",
  "import { api } from '@/lib/api';",
  "import { ChatWindow } from '@/components/chat/ChatWindow';",
  "import { CreateRoomModal } from '@/components/chat/RoomList';",
  "import type { Room } from '@chat/types';",
  "",
  "function IconCommunity() {",
  "  return (",
  "    <svg width='26' height='26' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.6'>",
  "      <path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/>",
  "      <circle cx='9' cy='7' r='4'/>",
  "      <path d='M23 21v-2a4 4 0 0 0-3-3.87'/>",
  "      <path d='M16 3.13a4 4 0 0 1 0 7.75'/>",
  "    </svg>",
  "  );",
  "}",
  "function IconForum() {",
  "  return (",
  "    <svg width='26' height='26' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.6'>",
  "      <path d='M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z'/>",
  "    </svg>",
  "  );",
  "}",
  "function IconGallery() {",
  "  return (",
  "    <svg width='26' height='26' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.6'>",
  "      <rect x='3' y='3' width='18' height='18' rx='2'/>",
  "      <circle cx='8.5' cy='8.5' r='1.5'/>",
  "      <polyline points='21 15 16 10 5 21'/>",
  "    </svg>",
  "  );",
  "}",
  "function IconInfo() {",
  "  return (",
  "    <svg width='26' height='26' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.6'>",
  "      <rect x='3' y='3' width='18' height='18' rx='2'/>",
  "      <line x1='9' y1='9' x2='15' y2='9'/>",
  "      <line x1='9' y1='13' x2='15' y2='13'/>",
  "      <line x1='9' y1='17' x2='12' y2='17'/>",
  "    </svg>",
  "  );",
  "}",
  "function IconCart() {",
  "  return (",
  "    <svg width='26' height='26' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='1.6'>",
  "      <circle cx='9' cy='21' r='1'/>",
  "      <circle cx='20' cy='21' r='1'/>",
  "      <path d='M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6'/>",
  "    </svg>",
  "  );",
  "}",
  "",
  "function PostRow({ category, title, count, onClick }: {",
  "  category: string;",
  "  title: string;",
  "  count?: number;",
  "  onClick?: () => void;",
  "}) {",
  "  const [hovered, setHovered] = useState(false);",
  "  return (",
  "    <div",
  "      onClick={onClick}",
  "      onMouseEnter={() => setHovered(true)}",
  "      onMouseLeave={() => setHovered(false)}",
  "      style={{",
  "        display: 'flex',",
  "        alignItems: 'center',",
  "        padding: '0 14px',",
  "        height: 44,",
  "        borderBottom: '1px solid #efefef',",
  "        background: hovered ? '#fafafa' : '#fff',",
  "        cursor: onClick ? 'pointer' : 'default',",
  "      }}",
  "    >",
  "      <span style={{",
  "        fontSize: 13.5, color: '#333', flex: 1,",
  "        overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', lineHeight: 1.4,",
  "      }}>",
  "        <span style={{ color: '#555' }}>[{category}]</span>",
  "        {' '}{title}",
  "      </span>",
  "      {count !== undefined && count > 0 && (",
  "        <span style={{",
  "          marginLeft: 8, minWidth: 22, height: 22, borderRadius: 11,",
  "          background: '#f0f0f0', color: '#666', fontSize: 11, fontWeight: 600,",
  "          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',",
  "          padding: '0 5px', flexShrink: 0,",
  "        }}>",
  "          {count}",
  "        </span>",
  "      )}",
  "    </div>",
  "  );",
  "}",
  "",
  "function SectionHeader({ title }: { title: string }) {",
  "  return (",
  "    <div style={{",
  "      padding: '11px 14px 9px', background: '#fff', borderBottom: '1px solid #ddd',",
  "      fontSize: 15, fontWeight: 700, color: '#111',",
  "    }}>",
  "      {title}",
  "    </div>",
  "  );",
  "}",
  "",
  "function SectionGap() {",
  "  return <div style={{ height: 10, background: '#f0f0f0' }} />;",
  "}",
  "",
  "function AdBlock() {",
  "  return (",
  "    <div style={{ background: '#fff', padding: '10px 14px 12px', borderBottom: '1px solid #efefef' }}>",
  "      <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 4 }}>",
  "        <span style={{ fontSize: 11, color: '#888' }}>\uD30C\uC6CC\uB9C1\uD06C</span>",
  "        <span style={{ fontSize: 10, color: '#888', border: '1px solid #ccc', padding: '0 3px', borderRadius: 2 }}>\uAD11\uACE0</span>",
  "        <span style={{ marginLeft: 'auto', fontSize: 11, color: '#aaa' }}>\uAD11\uACE0\uC2E0\uCCAD</span>",
  "      </div>",
  "      <div style={{ fontSize: 14, fontWeight: 700, color: '#c0392b', marginBottom: 2 }}>",
  "        \uCC44\uD305\uBC29\uC744 \uB9CC\uB4E4\uC5B4 \uB300\uD654\uD574\uBCF4\uC138\uC694",
  "      </div>",
  "      <div style={{ fontSize: 11, color: '#999', marginBottom: 3 }}>chat.example.com</div>",
  "      <div style={{ fontSize: 12, color: '#555' }}>",
  "        \uC2E4\uC2DC\uAC04 \uCC44\uD305\uC73C\uB85C \uBE60\uB974\uAC8C \uC18C\uD1B5\uD558\uC138\uC694",
  "      </div>",
  "    </div>",
  "  );",
  "}",
  "",
  "function ScrollToTopBtn({ containerRef }: { containerRef: RefObject<HTMLDivElement | null> }) {",
  "  return (",
  "    <div",
  "      onClick={() => containerRef.current?.scrollTo({ top: 0, behavior: 'smooth' })}",
  "      style={{",
  "        position: 'fixed', bottom: 22, right: 16,",
  "        background: '#555', color: '#fff', fontSize: 12, padding: '7px 14px',",
  "        borderRadius: 20, cursor: 'pointer', boxShadow: '0 2px 8px rgba(0,0,0,0.25)',",
  "        userSelect: 'none', zIndex: 200,",
  "      }}",
  "    >",
  "      \u2191 \uB9F8\uC704\uB85C",
  "    </div>",
  "  );",
  "}",
  "",
  "export default function ChatPage() {",
  "  const router = useRouter();",
  "  const clear = useAuthStore((s) => s.clear);",
  "  const accessToken = useAuthStore((s) => s.accessToken);",
  "  const user = useAuthStore((s) => s.user);",
  "  const rooms = useChatStore((s) => s.rooms);",
  "  const setRooms = useChatStore((s) => s.setRooms);",
  "",
  "  const [selectedRoom, setSelectedRoom] = useState<Room | null>(null);",
  "  const [showModal, setShowModal] = useState(false);",
  "  const scrollRef = useRef<HTMLDivElement>(null);",
  "",
  "  useEffect(() => {",
  "    if (!accessToken) router.replace('/login');",
  "  }, [accessToken, router]);",
  "",
  "  useEffect(() => {",
  "    if (accessToken) {",
  "      api.get<{ data: Room[] }>('/rooms').then((res) => setRooms(res.data.data));",
  "    }",
  "  }, [accessToken, setRooms]);",
  "",
  "  function handleCreated(room: Room) {",
  "    setRooms([room, ...rooms]);",
  "    setSelectedRoom(room);",
  "  }",
  "",
  "  function handleLogout() {",
  "    clear();",
  "    router.replace('/login');",
  "  }",
  "",
  "  if (!accessToken) return null;",
  "",
  "  const groupRooms = rooms.filter((r) => r.isGroup);",
  "  const dmRooms    = rooms.filter((r) => !r.isGroup);",
  "  const popular = [...groupRooms].sort((a, b) => b.members.length - a.members.length).slice(0, 5);",
  "  const recommended = [...rooms].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).slice(0, 5);",
  "  const latestByMsg = [...rooms].sort((a, b) => {",
  "    const aT = a.messages?.[a.messages.length - 1]?.createdAt ?? a.createdAt;",
  "    const bT = b.messages?.[b.messages.length - 1]?.createdAt ?? b.createdAt;",
  "    return new Date(bT).getTime() - new Date(aT).getTime();",
  "  }).slice(0, 8);",
  "",
  "  function cat(r: Room) { return r.isGroup ? '\uADF8\uB8F9' : 'DM'; }",
  "",
  "  const HEADER_H = 48;",
  "  const NAV_H    = 90;",
  "",
  "  return (",
  "    <div style={{",
  "      maxWidth: 430, margin: '0 auto', minHeight: '100vh', background: '#f0f0f0',",
  "      fontFamily: '\"Apple SD Gothic Neo\",\"Malgun Gothic\",Arial,sans-serif', position: 'relative',",
  "    }}>",
  "",
  "      <header style={{",
  "        position: 'sticky', top: 0, zIndex: 100, height: HEADER_H,",
  "        background: '#1a76c8', display: 'flex', alignItems: 'center', padding: '0 14px',",
  "      }}>",
  "        <div style={{ flex: 1 }} />",
  "        <div style={{",
  "          position: 'absolute', left: '50%', transform: 'translateX(-50%)',",
  "          fontWeight: 900, fontSize: 26, fontStyle: 'italic',",
  "          color: '#fff', letterSpacing: -1, lineHeight: 1,",
  "        }}>SLR</div>",
  "        <div style={{ flex: 1, display: 'flex', justifyContent: 'flex-end', alignItems: 'center' }}>",
  "          {user?.username ? (",
  "            <button onClick={handleLogout}",
  "              style={{ background: 'none', border: 'none', color: '#fff', fontSize: 12, fontWeight: 700, cursor: 'pointer' }}",
  "            >LOGOUT</button>",
  "          ) : (",
  "            <span style={{ color: '#fff', fontSize: 12, fontWeight: 700 }}>LOGIN</span>",
  "          )}",
  "        </div>",
  "      </header>",
  "",
  "      <nav style={{",
  "        position: 'sticky', top: HEADER_H, zIndex: 99,",
  "        background: '#fff', borderBottom: '1px solid #e0e0e0',",
  "      }}>",
  "        <div style={{ display: 'flex', borderBottom: '1px solid #f2f2f2' }}>",
  "          {([",
  "            { icon: <IconCommunity />, label: '\uCEE4\uBBA4\uB2C8\uD2F0' },",
  "            { icon: <IconForum />,     label: '\uD3EC\uB7FC', action: () => setShowModal(true) },",
  "            { icon: <IconGallery />,   label: '\uAE54\uB7EC\uB9AC' },",
  "            { icon: <IconInfo />,      label: '\uC778\uD3EC\uBA54\uC774\uC158' },",
  "          ] as { icon: React.ReactNode; label: string; action?: () => void }[]).map(({ icon, label, action }) => (",
  "            <button key={label} onClick={action} style={{",
  "              flex: 1, display: 'flex', flexDirection: 'column',",
  "              alignItems: 'center', justifyContent: 'center',",
  "              padding: '10px 0 8px', background: 'none', border: 'none',",
  "              cursor: action ? 'pointer' : 'default', fontSize: 10.5, color: '#444', gap: 4,",
  "            }}>",
  "              {icon}",
  "              <span>{label}</span>",
  "            </button>",
  "          ))}",
  "        </div>",
  "        <div style={{ display: 'flex' }}>",
  "          <button style={{",
  "            display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',",
  "            padding: '8px 0 7px', background: 'none', border: 'none',",
  "            cursor: 'default', fontSize: 10.5, color: '#444', gap: 4, width: '25%',",
  "          }}>",
  "            <IconCart />",
  "            <span>\uB9C8\uCF13</span>",
  "          </button>",
  "        </div>",
  "      </nav>",
  "",
  "      <div ref={scrollRef} style={{ overflowY: 'auto' }}>",
  "        {selectedRoom ? (",
  "          <div style={{ display: 'flex', flexDirection: 'column', height: `calc(100vh - ${HEADER_H + NAV_H}px)` }}>",
  "            <div style={{",
  "              background: '#fff', borderBottom: '1px solid #e0e0e0',",
  "              padding: '9px 14px', display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0,",
  "            }}>",
  "              <button onClick={() => setSelectedRoom(null)}",
  "                style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#1a76c8', fontSize: 14, fontWeight: 700, padding: '2px 8px 2px 0' }}",
  "              >",
  "                \u2190 \uBAA9\uB85D",
  "              </button>",
  "              <span style={{ fontWeight: 700, fontSize: 15, color: '#111' }}>{selectedRoom.name}</span>",
  "              <span style={{ fontSize: 12, color: '#aaa', marginLeft: 2 }}>",
  "                {selectedRoom.isGroup ? `${selectedRoom.members.length}\uBA85` : 'DM'}",
  "              </span>",
  "            </div>",
  "            <div style={{ flex: 1, overflow: 'hidden' }}>",
  "              <ChatWindow roomId={selectedRoom.id} />",
  "            </div>",
  "          </div>",
  "        ) : (",
  "          <>",
  "            <div style={{ background: '#fff' }}>",
  "              <SectionHeader title='\uC778\uAE30\uAE00' />",
  "              {popular.length === 0",
  "                ? <PostRow category='\uC548\uB0B4' title='\uCC44\uD305\uBC29\uC744 \uB9CC\uB4E4\uC5B4\uBCF4\uC138\uC694' />",
  "                : popular.map((r) => <PostRow key={r.id} category={cat(r)} title={r.name} count={r.members.length} onClick={() => setSelectedRoom(r)} />)",
  "              }",
  "            </div>",
  "            <SectionGap />",
  "            <div style={{ background: '#fff' }}>",
  "              <SectionHeader title='\uCD94\uCC9C\uC778\uAE30\uAE00' />",
  "              {recommended.length === 0",
  "                ? <PostRow category='\uC548\uB0B4' title='\uCC44\uD305\uBC29\uC774 \uC5C6\uC2B5\uB2C8\uB2E4' />",
  "                : recommended.map((r) => <PostRow key={r.id} category={cat(r)} title={r.name} count={r.members.length} onClick={() => setSelectedRoom(r)} />)",
  "              }",
  "            </div>",
  "            <AdBlock />",
  "            <SectionGap />",
  "            <div style={{ background: '#fff' }}>",
  "              <SectionHeader title='\uCD5C\uC2E0\uAE00' />",
  "              {latestByMsg.length === 0",
  "                ? <PostRow category='\uC548\uB0B4' title='\uCC44\uD305\uBC29\uC774 \uC5C6\uC2B5\uB2C8\uB2E4' />",
  "                : latestByMsg.map((r) => <PostRow key={r.id} category={cat(r)} title={r.name} count={r.members.length} onClick={() => setSelectedRoom(r)} />)",
  "              }",
  "            </div>",
  "            <SectionGap />",
  "            <div style={{ background: '#fff' }}>",
  "              <SectionHeader title='\uC2DC\uC7A5\uC815\uBCF4' />",
  "              {dmRooms.length === 0",
  "                ? <PostRow category='\uC548\uB0B4' title='1:1 \uCC44\uD305\uBC29\uC774 \uC5C6\uC2B5\uB2C8\uB2E4' />",
  "                : dmRooms.map((r) => <PostRow key={r.id} category={cat(r)} title={r.name} count={r.members.length} onClick={() => setSelectedRoom(r)} />)",
  "              }",
  "            </div>",
  "            <SectionGap />",
  "          </>",
  "        )}",
  "      </div>",
  "",
  "      {!selectedRoom && <ScrollToTopBtn containerRef={scrollRef} />}",
  "      {showModal && <CreateRoomModal onClose={() => setShowModal(false)} onCreated={handleCreated} />}",
  "    </div>",
  "  );",
  "}",
].join('\n');

fs.writeFileSync(out, code, { encoding: 'utf8' });
console.log('Written:', out, '| lines:', code.split('\n').length);
